matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6-dev"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=build
    - python: "3.7-dev"
      env: TOXENV=lint
    - python: "3.7-dev"
      env: TOXENV=py37

install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls